import { Adventure, Accommodation, Destination, College } from "./types";

export const destinations: Destination[] = [
  {
    id: "1",
    name: "Charminar, Hyderabad",
    description: "An iconic 16th-century mosque and monument located in Hyderabad, India.",
    highlights: ["Historical Mosque", "Laad Bazaar", "Street Food", "Architecture"],
    imageUrl: "/destinations/charminar.jpg",
  },
  {
    id: "2",
    name: "Goa Beaches",
    description: "Famous for its beaches, ranging from popular stretches at Baga and Palolem to those in laid-back fishing villages such as Agonda.",
    highlights: ["Beach Parties", "Water Sports", "Seafood", "Portuguese Architecture"],
    imageUrl: "/destinations/goa.jpg",
  },
];

export const adventures: Adventure[] = [
  {
    id: "a1",
    name: "Scuba Diving in Grande Island",
    description: "Experience the underwater world with crystal clear waters and diverse marine life.",
    location: "Goa",
    category: "water",
    price: 3500,
    imageUrl: "/adventures/scuba.jpg",
  },
  {
    id: "a2",
    name: "Kayaking through Mangroves",
    description: "Paddle through the serene backwaters and explore the unique ecosystem.",
    location: "Goa",
    category: "water",
    price: 1500,
    imageUrl: "/adventures/kayak.jpg",
  },
  {
    id: "a3",
    name: "Heritage Walk in Old City",
    description: "Discover the hidden gems and history of the old city surrounding Charminar.",
    location: "Hyderabad",
    category: "cultural",
    price: 500,
    imageUrl: "/adventures/heritage-walk.jpg",
  },
];

export const accommodations: Accommodation[] = [
  {
    id: "h1",
    name: "The Grand Residency",
    type: "hotel",
    description: "Luxury stay with a view of the city skyline.",
    location: "Hyderabad",
    pricePerNight: 5000,
    amenities: ["Wi-Fi", "Pool", "Gym", "Restaurant"],
    imageUrl: "/hotels/grand-residency.jpg",
  },
  {
    id: "h2",
    name: "Backpackers Haven",
    type: "hostel",
    description: "Affordable and social accommodation for travelers.",
    location: "Goa",
    pricePerNight: 800,
    amenities: ["Common Room", "Dormitory", "Kitchen"],
    imageUrl: "/hotels/hostel.jpg",
  },
  {
    id: "h3",
    name: "Heritage Homestay",
    type: "room",
    description: "Experience local culture in a traditional home.",
    location: "Hyderabad",
    pricePerNight: 2000,
    amenities: ["Breakfast", "Garden"],
    imageUrl: "/hotels/homestay.jpg",
  },
];

export const colleges: College[] = [
  {
    id: "c1",
    name: "Tech University of Hyderabad",
    location: "Hyderabad",
    description: "A leading institution for engineering and technology studies with state-of-the-art labs and research facilities.",
    tuition: 150000,
    majors: ["Computer Science", "Electronics", "Mechanical Engineering"],
    imageUrl: "/colleges/tech-uni.jpg",
    ranking: 15,
    accreditation: "NAAC A++",
    placementRate: 95,
    highestPackage: 4500000,
    facilities: ["High-speed Wi-Fi", "Modern Labs", "Digital Library", "Sports Complex"],
    established: 1995,
    website: "https://tuh.edu.in",
  },
  {
    id: "c2",
    name: "Coastal Institute of Arts",
    location: "Goa",
    description: "A premier college for fine arts and design located near the coast, offering a creative environment for aspiring artists.",
    tuition: 80000,
    majors: ["Visual Arts", "Design", "Art History"],
    imageUrl: "/colleges/arts-inst.jpg",
    ranking: 8,
    accreditation: "NAAC A",
    placementRate: 85,
    highestPackage: 1200000,
    facilities: ["Art Studios", "Gallery", "Open-air Theatre", "Hostel"],
    established: 2005,
    website: "https://coastalarts.edu.in",
  },
  {
    id: "c3",
    name: "Global Business School",
    location: "Hyderabad",
    description: "Excellence in business management and entrepreneurship, preparing future leaders for the global market.",
    tuition: 250000,
    majors: ["Business Administration", "Finance", "Marketing"],
    imageUrl: "/colleges/business-school.jpg",
    ranking: 20,
    accreditation: "EQUIS",
    placementRate: 98,
    highestPackage: 6000000,
    facilities: ["Business Hub", "Auditorium", "Global Networking Center", "Premium Hostel"],
    established: 2010,
    website: "https://gbs-global.edu.in",
  },
];
