import { Adventure, Accommodation, Destination, College } from "./types";

export const destinations: Destination[] = [
  {
    id: "1",
    name: "Charminar, Hyderabad",
    description: "An iconic 16th-century mosque and monument located in Hyderabad, India.",
    highlights: ["Historical Mosque", "Laad Bazaar", "Street Food", "Architecture"],
    imageUrl: "/destinations/charminar.jpg",
  },
  {
    id: "2",
    name: "Goa Beaches",
    description: "Famous for its beaches, ranging from popular stretches at Baga and Palolem to those in laid-back fishing villages such as Agonda.",
    highlights: ["Beach Parties", "Water Sports", "Seafood", "Portuguese Architecture"],
    imageUrl: "/destinations/goa.jpg",
  },
];

export const adventures: Adventure[] = [
  {
    id: "a1",
    name: "Scuba Diving in Grande Island",
    description: "Experience the underwater world with crystal clear waters and diverse marine life.",
    location: "Goa",
    category: "water",
    price: 3500,
    imageUrl: "/adventures/scuba.jpg",
  },
  {
    id: "a2",
    name: "Kayaking through Mangroves",
    description: "Paddle through the serene backwaters and explore the unique ecosystem.",
    location: "Goa",
    category: "water",
    price: 1500,
    imageUrl: "/adventures/kayak.jpg",
  },
  {
    id: "a3",
    name: "Heritage Walk in Old City",
    description: "Discover the hidden gems and history of the old city surrounding Charminar.",
    location: "Hyderabad",
    category: "cultural",
    price: 500,
    imageUrl: "/adventures/heritage-walk.jpg",
  },
];

export const accommodations: Accommodation[] = [
  {
    id: "h1",
    name: "The Grand Residency",
    type: "hotel",
    description: "Luxury stay with a view of the city skyline.",
    location: "Hyderabad",
    pricePerNight: 5000,
    amenities: ["Wi-Fi", "Pool", "Gym", "Restaurant"],
    imageUrl: "/hotels/grand-residency.jpg",
  },
  {
    id: "h2",
    name: "Backpackers Haven",
    type: "hostel",
    description: "Affordable and social accommodation for travelers.",
    location: "Goa",
    pricePerNight: 800,
    amenities: ["Common Room", "Dormitory", "Kitchen"],
    imageUrl: "/hotels/hostel.jpg",
  },
  {
    id: "h3",
    name: "Heritage Homestay",
    type: "room",
    description: "Experience local culture in a traditional home.",
    location: "Hyderabad",
    pricePerNight: 2000,
    amenities: ["Breakfast", "Garden"],
    imageUrl: "/hotels/homestay.jpg",
  },
];

export const colleges: College[] = [
  {
    id: "iisc-bangalore",
    name: "Indian Institute of Science (IISc)",
    location: "Bangalore",
    description: "India's premier institute for advanced scientific and technological research and education. Founded by Jamsetji Tata in 1909.",
    tuition: 35000,
    majors: ["Physics", "Biological Sciences", "Mechanical Engineering", "Materials Engineering"],
    imageUrl: "/colleges/iisc.jpg",
    ranking: 1,
    accreditation: "NAAC A++",
    placementRate: 92,
    highestPackage: 8500000,
    facilities: ["Supercomputing Center", "Nuclear Magnetic Resonance Facility", "J.R.D. Tata Memorial Library"],
    established: 1909,
    website: "https://iisc.ac.in",
  },
  {
    id: "iit-bombay",
    name: "IIT Bombay",
    location: "Mumbai",
    description: "Recognized as a worldwide leader in the field of engineering education and research. It is known for its outstanding faculty and world-class students.",
    tuition: 215000,
    majors: ["Computer Science", "Electrical Engineering", "Aerospace Engineering", "Chemical Engineering"],
    imageUrl: "/colleges/iitb.jpg",
    ranking: 3,
    accreditation: "Institute of Eminence",
    placementRate: 98,
    highestPackage: 16000000,
    facilities: ["Shailesh J. Mehta School of Management", "NVLI Lab", "Industrial Design Centre"],
    established: 1958,
    website: "https://iitb.ac.in",
  },
  {
    id: "iit-delhi",
    name: "IIT Delhi",
    location: "New Delhi",
    description: "One of the twenty-three IITs created to be Centres of Excellence for training, research and development in science, engineering and technology in India.",
    tuition: 225000,
    majors: ["Computer Science", "Textile and Fibre Engineering", "Civil Engineering", "Biochemical Engineering"],
    imageUrl: "/colleges/iitd.jpg",
    ranking: 2,
    accreditation: "Institute of Eminence",
    placementRate: 96,
    highestPackage: 14000000,
    facilities: ["Central Research Facility", "Nanoscience Facility", "Technopark"],
    established: 1961,
    website: "https://iitd.ac.in",
  },
  {
    id: "jnu-delhi",
    name: "Jawaharlal Nehru University",
    location: "New Delhi",
    description: "A public central university known for leading faculties and research emphasis on liberal arts and applied sciences.",
    tuition: 1200,
    majors: ["International Studies", "Social Sciences", "Arts and Aesthetics", "Life Sciences"],
    imageUrl: "/colleges/jnu.jpg",
    ranking: 10,
    accreditation: "NAAC A++",
    placementRate: 78,
    highestPackage: 3500000,
    facilities: ["Hellenic Studies Center", "Special Centre for Nanosciences", "Advanced Instrumentation Facility"],
    established: 1969,
    website: "https://jnu.ac.in",
  },
  {
    id: "iit-madras",
    name: "IIT Madras",
    location: "Chennai",
    description: "Consistently ranked as the top engineering institute in India. It is a residential institute with nearly 550 faculty and 8,000 students.",
    tuition: 210000,
    majors: ["Ocean Engineering", "Metallurgical and Materials Engineering", "Computer Science", "Physics"],
    imageUrl: "/colleges/iitm.jpg",
    ranking: 1,
    accreditation: "Institute of Eminence",
    placementRate: 97,
    highestPackage: 15000000,
    facilities: ["IITM Research Park", "Ocean Engineering Department", "Wildlife-rich Campus"],
    established: 1959,
    website: "https://iitm.ac.in",
  },
];
